### ISSUE TITLE
adtpro not finding serial port under windows 10

### ISSUE THREAD

**Issue by kdevries** [ADTPro/adtpro#144]
Hi All,

Adtpro (tried version **21.0** and **2.0.3**) under windows 10 with "**java 8 update 311 (64-bit)**" and with the 64 bit drivers for the official USB cable "**USB to RS-232 Adapter**" sold on Retrofloppy installed gives me the error:

**"There are no serial ports, or the serial library RXTX is not installed or vissible"**

I have checked in device management and looks at the files used by the "**USB Serial Convertor**" and "**USB Serial Port (COM4)**" under "c:/windows/system32" and "c:/windows/system32/drivers"and those files are the same sizes as the ones in "**CDM v2.12.36.4 WHQL Certified\amd64**" the files in "CDM v2.12.36.4 WHQL Certified\i386" have different sizes

So I do have a **64 bit java version** and the **64 bit drivers** installed
I am not lost why adtpro can not find the serial port

Friendly greetings,

Kevin

**Comment by kdevries** [comment]
this is java output iuf I run from administrator command prompt:

c:\Users\kdevries\Desktop\ADTPro-2.1.0\lib>java -jar ADTPro-2.1.0.jar
ADTPro Server version 2.1.0

Exception in thread "main" java.lang.NoClassDefFoundError: jssc/SerialPortException
        at org.adtpro.gui.SerialConfig.enumeratePorts(Unknown Source)
        at org.adtpro.gui.SerialConfig.<init>(Unknown Source)
        at org.adtpro.gui.SerialConfig.allocateSingleton(Unknown Source)
        at org.adtpro.gui.SerialConfig.getSingleton(Unknown Source)
        at org.adtpro.gui.Gui.<init>(Unknown Source)
        at org.adtpro.ADTPro.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: jssc.SerialPortException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)

**Comment by kdevries** [comment]
Had to run the included adtpro.bat file :)
