### ISSUE TITLE
Can't load JSSC and missing RXTX errors

### ISSUE THREAD

**Issue by StargeezerLabs** [ADTPro/adtpro#179]
Hi:
I am struggling to overcome an issue with the error of "serial library RXTX is not installed or visible."
I am using the following:
Macbook Pro: Ventura 13.5.2, Keyspan USA-19HS, ADTPro 2.1.0.  
I tried to investigate if ADT is not finding something that is installed.  I launched ADTPro via ADTPro.command and received the following error in the cli:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load the jssc library: Couldn't load library library jssc
	at jssc.SerialNativeInterface.<clinit>(SerialNativeInterface.java:90)
	at jssc.SerialPortList.<clinit>(SerialPortList.java:43)
	at org.adtpro.transport.SerialTransport.getPortNames(Unknown Source)
	at org.adtpro.gui.SerialConfig.enumeratePorts(Unknown Source)
	at org.adtpro.gui.SerialConfig.<init>(Unknown Source)
	at org.adtpro.gui.SerialConfig.allocateSingleton(Unknown Source)
	at org.adtpro.gui.SerialConfig.getSingleton(Unknown Source)
	at org.adtpro.gui.Gui.<init>(Unknown Source)
	at org.adtpro.ADTPro.main(Unknown Source)`
I can see the jssc lbrary in the subfolder `lib` in the ADTPro folder but I am puzzled as to why ADT can't find it.
Thanks in advance for any assistance.
Mark

**Comment by StargeezerLabs** [comment]
Found solution in older thread.
